name: Serenity UI API Tests

on:
  push:
    branches:
      - develop
      - main

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      # Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Setup Java
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      # Install Chrome
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      # Run Serenity Tests
      - name: Run Tests
        run: |
          mvn clean verify \
          -Dwebdriver.driver=chrome \
          -Dheadless.mode=true

      # Generate Serenity Report
      - name: Generate Serenity Report
        run: mvn serenity:aggregate

      # Deploy Report to GitHub Pages
      - name: Deploy Serenity Report
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/site/serenity
